set(NEBULA_CXX_COMPILER_FLAGS "")
macro(AppendFlag flag min max)
    if (MSVC_VERSION GREATER_EQUAL ${min} AND MSVC_VERSION LESS_EQUAL ${max})
        list(APPEND NEBULA_CXX_COMPILER_FLAGS ${flag})
    endif ()
endmacro()

macro(AppendFlag flag min)
    if (MSVC_VERSION GREATER_EQUAL ${min})
        list(APPEND NEBULA_CXX_COMPILER_FLAGS ${flag})
    endif ()
endmacro()

AppendFlag("/permissive-" 1910)
AppendFlag("/Zc:__cplusplus" 1914)
AppendFlag("/Zc:__STDC__" 1932)
AppendFlag("/Zc:enumTypes" 1934)
AppendFlag("/Zc:externConstexpr" 1913 1936)
AppendFlag("/Zc:inline" 1800)
AppendFlag("/Zc:lambda" 1928 1936)
AppendFlag("/Zc:templateScope" 1935)
AppendFlag("/Zc:ternary" 1910 1912)
AppendFlag("/Zc:throwingNew" 1900)
AppendFlag("/Zc:trigraphs" 1915)